### ISSUE TITLE
Merge request workflow broken

### ISSUE THREAD

**Issue by richard-russell** [hashicorp/tfc-workflows-gitlab#30]
The merge request workflow fails as the plan is run not as a speculative but an applyable plan. This leads the `check_run_status` job to fail, as it's expecting a status that can only happen with a speculative plan. The pipeline fails and the workspace is left in a locked state.

![Image](https://github.com/user-attachments/assets/780423ca-fb9d-4a04-835f-1b022a7d1ce1)

I think this happens because of a problem with precedence of variables.

`Base.gitlab-ci.yml` sets default values of SPECULATIVE and PLAN_ONLY to be non-speculative:
```
.tfc:upload_configuration:
  variables:
    SPECULATIVE: false

.tfc:create_run:
  variables:
    PLAN_ONLY: false
```

`.gitlab-ci.yml` sets these variables to be correct for a speculative plan if the pipeline source is a merge request event:
```
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
      variables:
        PLAN_ONLY: "true"
        SPECULATIVE: "true"
```

The intention is that these MR-specific values from `.gitlab-ci.yml` will override the values from the included `Base.gitlab-ci.yml`.

However, the `.gitlab-ci.yml` variables are set at the global level, and the values in `Base.gitlab-ci.yml` are set at the job level, so the precedence is the opposite of what is intended.
